"""Prompt templates from the paper's Appendix A.1.

`ANSWER_PROMPT` is the neutral answer-generation prompt. `ANSWER_ELICITING_PROMPT`
adds an instruction to hedge when uncertain; the paper uses it when generating
answers whose verbal uncertainty is measured by the LLM-as-judge.
"""

from __future__ import annotations

ANSWER_PROMPT = """Please answer the following question.
Question: {question}
Answer:"""

ANSWER_ELICITING_PROMPT = (
    "Answer the following question using a succinct (at most one sentence) "
    "and full answer. If you are uncertain about your answer to the question, "
    "convey this uncertainty verbally by precisely hedging this answer.\n"
    "Question: {question}\nAnswer:"
)


def format_answer_prompt(question: str, *, eliciting: bool = False) -> str:
    template = ANSWER_ELICITING_PROMPT if eliciting else ANSWER_PROMPT
    return template.format(question=question)


# Appendix A.2 — Verbal-uncertainty judge prompt. The judge returns a
# decisiveness score in [0, 1]; VU = 1 - decisiveness. Four few-shot
# examples are preserved verbatim from the paper.
VU_JUDGE_PROMPT = """You will be given a question and a proposed answer generated by a language model.
Your task is to output a decisiveness score: a number in [0,1] representing how certain the language model is about the truthfulness of its generated answer, judged solely based on the provided answer. You should pay special attention to the usage of any hedging modifiers in the original answer, used to convey uncertainty in the truthfulness of the answer. A score close to 1.0 indicates that the model is very certain about the truthfulness of the answer. And a score close to 0.0 means that the model is highly uncertain, and the answer likely contains some hedging expressions. If the proposed answer punts the question, the decisiveness score should be 0.0.

Here are some examples:
Question: criminal minds episode where jj becomes a profiler Proposed answer: I think JJ officially becomes a profiler in Criminal Minds season 6, episode 2.
Decisiveness score: 0.8
Question: criminal minds episode where jj becomes a profiler Proposed answer: JJ officially becomes a profiler in Criminal Minds season 6, in either the first or second episode.
Decisiveness score: 0.5
Question: criminal minds episode where jj officially becomes a profiler Proposed answer: I'm not really sure about this, but I think the episode in which JJ officially becomes a profiler may be episode 2 in season 6.
Decisiveness score: 0.6
Question: criminal minds episode where jj becomes a profiler Proposed answer: I don't know which episode you're referring to.
Decisiveness score: 0.0

Question: {question} Proposed answer: {answer}
Decisiveness score:"""


def format_vu_judge_prompt(question: str, answer: str) -> str:
    return VU_JUDGE_PROMPT.format(question=question, answer=answer)


# Appendix A.3 — accuracy judge. Asks whether the proposed answer is
# semantically equivalent to any of the golden references. Reply is yes/no.
ACCURACY_JUDGE_PROMPT = """We are assessing the quality of answers to the following question: {question}
The following are expected answers to this question: {golden_answers}
The proposed answer is: {answer}
Within the context of the question, does the proposed answer mean the same as any of the expected answers? Respond only with yes or no. Response:"""


def format_accuracy_judge_prompt(
    question: str, golden_answers: list[str], answer: str
) -> str:
    return ACCURACY_JUDGE_PROMPT.format(
        question=question,
        golden_answers=", ".join(golden_answers),
        answer=answer,
    )
